export enum UserActions {
	LOG_IN = "LOG_IN",
	LOG_OUT = "LOG_OUT",
}

export enum TodoListActions {
	SET_FILTER = "SET_FILTER",
	RESET_FILTER = "RESET_FILTER",
	DELETE_ALL = "DELETE_ALL",
	TODOS_LOAD_START = "TODOS_LOAD_START",
	TODOS_LOAD_ERROR = "TODOS_LOAD_ERROR",
	TODOS_LOAD_COMPLETE = "TODOS_LOAD_COMPLETE",
}

export enum TodoActions {
	ADD_TODO = "ADD_TODO",
	DELETE_TODO = "DELETE_TODO",
	TOGGLE_TODO = "TOGGLE_TODO",
	TOGGLE_IMPORTANT = "TOGGLE_IMPORTANT",
}

export enum TodoFilters {
	SHOW_ALL = "SHOW_ALL",
	SHOW_IMPORTANT = "SHOW_IMPORTANT",
	SHOW_COMPLETED = "SHOW_COMPLETED",
}

export enum GlobalErrorActons {
	SET_GLOBAL_ERROR = "SET_GLOBAL_ERROR",
	UNSET_GLOBAL_ERROR = "UNSET_GLOBAL_ERROR",
}
